fix: fixed maxQueryLimit validation
forcedotcom/sfdx-core pull request #358
Opened 2021-01-20 23:04 UTC by WillieRuemmele

@W-8768271@

2021-01-20 23:28 UTC, shetzel requested changes
Nits, but will make the test output more explicit and self-documenting

2021-01-20 23:28 UTC, shetzel commented on test/unit/config/configTest.ts
> +        it('will throw an error', async () => {
```suggestion
        it('will throw an error when the value is mixed alphanumeric', async () => {
```

2021-01-20 23:28 UTC, shetzel commented on test/unit/config/configTest.ts
> +        it('will throw an error', async () => {
```suggestion
        it('will throw an error when the value is not a number', async () => {
```

2021-01-20 23:28 UTC, shetzel commented on test/unit/config/configTest.ts
> +        it('will set config value', async () => {
```suggestion
        it('will set config value when the value is a stringified number', async () => {
```

2021-01-20 23:28 UTC, shetzel commented on test/unit/config/configTest.ts
> +        it('will set config value', async () => {
```suggestion
        it('will set config value when the value is a number', async () => {
```

2021-01-21 03:14 UTC, shetzel approved these changes

2021-02-04 21:57 UTC, peternhale approved these changes

2021-02-04 22:00 UTC, merged