fix: return all info from AuthInfo.listAllAuthorizations
forcedotcom/sfdx-core pull request #449
Opened 2021-07-30 17:23 UTC by mdonnalley

Return more information from `AuthInfo.listAllAuthorizations`

@W-9670252@
@ W-9680192@

2021-07-30 17:54 UTC, peternhale requested changes
@mdonnalley I was expecting a change to SfOrg
```
export type SfOrg = {
  alias: Optional<string>;
  username: Optional<string>;
  orgId: Optional<string>;
  instanceUrl: Optional<string>;
  accessToken?: string;
  oauthMethod?: 'jwt' | 'web' | 'token' | 'unknown';
  error?: string;
} & SfEntry;
```

to 

```export type SfOrg = {
  aliases: Optional<string[]>;
  username: Optional<string>;
  orgId: Optional<string>;
  instanceUrl: Optional<string>;
  accessToken?: string;
  oauthMethod?: 'jwt' | 'web' | 'token' | 'unknown';
  error?: string;
} & SfEntry;
```

2021-08-02 11:46 UTC, peternhale approved these changes

2021-08-02 16:13 UTC, peternhale approved these changes

2021-08-02 16:23 UTC, RodEsp commented on src/org/authInfo.ts
> +          isScratchOrg,
```suggestion
          isScratchOrg = Boolean(devHubUsername),
```

2021-08-02 16:23 UTC, RodEsp commented on src/org/authInfo.ts
> +        const isScratchOrg = Boolean(devHubUsername);
```suggestion
        const { orgId, instanceUrl, devHubUsername } = authInfo.getFields();
```

2021-08-02 16:30 UTC, RodEsp requested changes

2021-08-02 16:30 UTC, RodEsp commented on src/org/authInfo.ts
> +        .map((c) => c.key);
Can we put a comment here about what exactly this is supposed to be doing please?

2021-08-02 16:34 UTC, RodEsp approved these changes

2021-08-02 16:37 UTC, merged