feat: add help section helper
forcedotcom/sfdx-core pull request #474
Opened 2021-09-09 20:07 UTC by peternhale

@W-9791511@

2021-09-09 20:09 UTC, peternhale commented on src/util/helpSectionUtils.ts
> +export const toHelpSection = (
produces a help section from the provided array of org/sfdx/env var enums

2021-09-09 20:34 UTC, mdonnalley requested changes
I think this is too specific to `sf` to belong in sfdx-core - is there a reason we wouldn't just put this in the custom help class?

2021-09-09 20:43 UTC, peternhale commented
> I think this is too specific to `sf` to belong in sfdx-core - is there a reason we wouldn't just put this in the custom help class?

@mdonnalley placing this in help class would require that each command reference that class. I could make this available in @salesforce/command.

2021-09-09 21:07 UTC, mdonnalley commented
> > I think this is too specific to `sf` to belong in sfdx-core - is there a reason we wouldn't just put this in the custom help class?
> 
> @mdonnalley placing this in help class would require that each command reference that class. I could make this available in @salesforce/command.

@peternhale yeah, I think that would make more sense

2021-09-10 12:09 UTC, peternhale commented
> > > I think this is too specific to `sf` to belong in sfdx-core - is there a reason we wouldn't just put this in the custom help class?
> > 
> > 
> > @mdonnalley placing this in help class would require that each command reference that class. I could make this available in @salesforce/command.
> 
> @peternhale yeah, I think that would make more sense

@mdonnalley moving this to @salesforce/command is complicated, since this code needs access to core v3 and command is dependent on v2. I can alias in v3, but seem pretty heavy at the moment.

2021-09-10 16:56 UTC, mdonnalley requested changes

2021-09-10 16:56 UTC, mdonnalley commented on package.json
> +    "@oclif/core": "^0.5.35",
this should be removed

2021-09-10 17:05 UTC, mdonnalley approved these changes

2021-09-10 17:23 UTC, merged