fix: add env vars from sfdx-cli init to envvars
forcedotcom/sfdx-core pull request #520
Opened 2022-02-08 21:15 UTC by peternhale

@W-10536395@

2020-06-15 12:09 UTC, AltiusRupert commented
I would like to add :  

1) most probably, relative dates (TODAY, LAST MIONTH, 3 MONTHS AGO) which are localized are probably in the same case

2) a similar but distinct problem : it looks like the text values in the "value" field are saved with the last admin user's text encoding. So I have issues comparing the same "value" field contents encoded in UTF8 (as saved by one user) and in ISO-8859-1, which produce different results.

2020-07-24 16:31 UTC, AltiusRupert commented
:poke: @clairebianchi

2022-02-08 21:17 UTC, peternhale commented
NOTE: While simply copy/paste/fix of sfdx-cli env var init logic into salesfirlce/cli was possible, I made the lion's share of the changes in core.
- Add env vars not present in well=known env vars
- Add the init functions from sfdx-cli to core.

2022-02-08 21:21 UTC, peternhale commented on src/config/envVars.ts
> +  public isAutoupdateDisabled(): boolean {
Function from sfdx-cli util/env.ts

2022-02-08 21:24 UTC, peternhale commented on src/globalInfo/whichCli.ts
> +export interface WhichCliInterface {
Forward looking to when env var scopes will needed to be resolved.

2022-02-10 23:02 UTC, mdonnalley requested changes

2022-02-11 19:18 UTC, RodEsp approved these changes

2022-02-11 20:29 UTC, merged

2022-02-11 22:54 UTC, RodEsp commented
@peternhale I thought there was still open discussion on this [in slack](https://salesforce-internal.slack.com/archives/C02J2118Z47/p1644607850992339?thread_ts=1644605732.525139&cid=C02J2118Z47). Why'd you go ahead and merge it?