Wr/deprecate
forcedotcom/sfdx-core pull request #532
Opened 2022-02-28 22:39 UTC by WillieRuemmele

@W-8776370@

removes the `@deprecated` methods/classes/code

2022-02-28 23:48 UTC, mdonnalley requested changes

2022-02-28 23:48 UTC, mdonnalley commented on src/config/config.ts
> -  /**
We need to keep these for the foreseeable future so that sfdx-core knows how to map between the username configs used by sfdx and the ones used by sf

2022-02-28 23:48 UTC, mdonnalley commented on src/config/config.ts
> -  {
same for this

2022-03-01 22:08 UTC, WillieRuemmele commented on README.md
> +import { SfError } from '@salesforce/core';
must've been an issue with the rebase. It looks clean now

2022-03-01 22:54 UTC, mdonnalley approved these changes

2022-03-02 15:52 UTC, merged